### ISSUE TITLE
Feature: User can view a stock's profile

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Stockio#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a stock's profile..

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
A user can search for a stock and view the stock's profile data accompanied by a daily price chart.

When the user types into a search bar and submits their search keywords, a matching stock and its profile is loaded from the Alpha Vantage API and displayed on the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Test the API to ensure that the data is available.
- [x] Make a container to hold stock profile data with tabs on top of the container.
- [x] Append the stock profile data to the container.
- [x] Add a chart with daily price data.
- [x] Make sure the tabs switch to different views.
- [x] Remove unnecessary CSS.
- [x] Fix bugs.
