### ISSUE TITLE
Feature: User can view a stock's valuation ratios.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Stockio#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a stock's valuation ratios and a chart of its daily close prices.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on the valuation tab to see a stock's valuation ratios and daily close prices. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure that valuation ratios are displayed
- [x] Make sure that chart with closing prices are displayed.
- [x] Make the application mobile friendly
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
