### ISSUE TITLE
Feature: User can view a stock's profitability ratios.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Stockio#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a stock's profitability ratios and a chart of daily close prices.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] ...Make sure that clicking the profitability tab shows a stock's profitability ratios and daily close prices chart.
- [x] ...Add styling to find button to match color scheme.
- [x] ...Add space between the stock data.
- [x] ...Remove unnecessary CSS.
- [x] ...Fix bugs
