### ISSUE TITLE
Feature: User can view a stock's liquidity ratios.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Stockio#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view a stock's liquidity ratios and a chart of daily close prices.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Make sure that a user can view a stock's liquidity ratios.
- [x] Make form on homepage appear below the image.
- [x] Make the find button larger.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
