### ISSUE TITLE
Feature: User can view a stock's solvency ratios.

### ISSUE THREAD

**Issue by Matthew-Abebe** [Matthew-Abebe/Stockio#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a stock's liquidity ratios and see a daily chart for close prices.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Make sure that stock solvency ratios are displaying.
- [x] Make sure daily close price chart is displaying.
- [x] Change color of line on chart to blue.
  - [x] Confirm that all previous functionality still works without errors.
